#!/usr/bin/env ruby
require "yaml"

args = ARGV.dup
args.shift if %w[e eval].include?(args.first)
in_place = !args.delete("-i").nil?
expression = args.shift
path = args.shift
data = YAML.load_file(path)

case expression
when ".user"
  puts data["user"]
when ".keys | length"
  puts Array(data["keys"]).length
when /\A\.keys\[(\d+)\]\.(filename|revoked|expires_at)\z/
  value = Array(data["keys"])[Regexp.last_match(1).to_i][Regexp.last_match(2)]
  puts value.nil? ? "null" : value
when /\Adel\(\.keys\[(\d+)\]\)\z/
  Array(data["keys"]).delete_at(Regexp.last_match(1).to_i)
when /\.keys\[(\d+)\]\.revoked = true.*\.keys\[\1\]\.revoked_at = "([^"]+)"/m
  key = Array(data["keys"])[Regexp.last_match(1).to_i]
  key["revoked"] = true
  key["revoked_at"] = Regexp.last_match(2)
else
  warn "unsupported yq expression: #{expression}"
  exit 2
end

File.write(path, data.to_yaml) if in_place
