name: ci

permissions:
  contents: write 
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate keys
        run: bash scripts/validate_keys.sh
      - name: Create PR (if not on main)
        if: github.ref != 'refs/heads/main'
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          gh pr create \
            --title "Add new SSH key (${BRANCH})" \
            --body "Automated PR for key addition" \
            --base main \
            --head "${BRANCH}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy keys
        run: bash scripts/deploy_keys.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup expired keys
        run: bash scripts/cleanup_expired.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}