name: ssh-keys

permissions:
  contents: write 
  pull-requests: write

on:
  push:
    paths:
      - 'keys/**'
      - 'meta/**'
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  validate:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate keys
        run: bash scripts/validate_keys.sh

  create_pr:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref != 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Create PR
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          if gh pr view "${BRANCH}" --repo "${GITHUB_REPOSITORY}" >/dev/null 2>&1; then
            echo "PR already exists, skip creation."
            exit 0
          fi
          gh pr create \
            --title "Add new SSH key (${BRANCH})" \
            --body "Automated PR for key addition" \
            --base main \
            --head "${BRANCH}" \
            --repo "${GITHUB_REPOSITORY}" \
            --label "auto‑merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy keys
        run: bash scripts/deploy_keys.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup expired keys
        run: bash scripts/cleanup_expired.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}